language: node_js
node_js: 
    - "6"
after_success:
    - coveralls
notification:
    email:
        recipients:
            - merdlera@oregonstate.edu
        on_success: never
        on_failure: change
